---
title: "Covid Interactive Exploration"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    theme: flatly
    navbar:
    - title: Made by Esteban Rucán
      href: https://github.com/estebanrucan
      align: right
runtime: shiny
resource_files:
- datasets/coordinates.RDS
- datasets/date.RDS
- datasets/owid-covid-data.csv
- datasets/owid-covid-data.RDS
- codes/global.R
- codes/statics.RData
---

```{r setup, include=FALSE}
load(file.path('codes', 'statics.RData'))
source(file.path('codes', 'global.R'))

today <- Sys.Date() %>% with_tz('UTC')

end <- covid_data %>%
  pull(date) %>%
  max()
```

Overwatch
=======================================================================


Column {data-width=500}
-----------------------------------------------------------------------

### New cases in last week per continent Over the Time

```{r}
evolution_of_cases() %>%
    group_by(continent) %>% 
    e_charts(date) %>%
    e_line(new_cases) %>% 
    e_animation(duration = 15000) %>% 
    e_tooltip(trigger = 'axis') %>% 
    e_axis_labels(x = 'Date',
                  y = 'New cases in a week') %>% 
    e_legend(bottom = '20') %>% 
    e_toolbox_feature("dataZoom") %>%
    e_toolbox_feature(feature = "reset") %>%
    e_toolbox_feature("dataView") %>%
    e_toolbox_feature("saveAsImage") %>% 
    e_datazoom(
        type = "slider", 
        toolbox = FALSE,
        bottom = -5
    ) %>% 
    e_x_axis(nameLocation = "center", 
           splitArea = list(show = FALSE),
           axisLabel = list(margin = 0)) %>% 
    e_y_axis(nameLocation = "center", 
             position = 'right',
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_theme_custom('codes//walden.project.json')
```


### Top Countries by Cases

```{r}
country_cases('2020-01-01', today) %>% 
    select(Country, Continent, `Total Cases`) %>%
    reactable::reactable(rownames = FALSE)
```


Column {data-width=500}
-----------------------------------------------------------------------

### ### New cases in last month per continent Over the Time

```{r}
evolution_of_cases() %>%
    group_by(continent) %>% 
    e_charts(date) %>%
    e_line(last_month_new_cases) %>% 
    e_animation(duration = 15000) %>% 
    e_tooltip(trigger = 'axis') %>% 
    e_axis_labels(x = 'Date',
                  y = 'New cases in last week') %>% 
    e_legend(bottom = '20') %>% 
    e_toolbox_feature("dataZoom") %>%
    e_toolbox_feature(feature = "reset") %>%
    e_toolbox_feature("dataView") %>%
    e_toolbox_feature("saveAsImage") %>% 
    e_datazoom(
        type = "slider", 
        toolbox = FALSE,
        bottom = -5
    ) %>% 
    e_x_axis(nameLocation = "center", 
           splitArea = list(show = FALSE),
           axisLabel = list(margin = 0)) %>% 
    e_y_axis(nameLocation = "center", 
             position = 'right',
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_theme_custom('codes//walden.project.json')
```


### Top Countries by Cases per Million

```{r}
country_cases_pm('2020-01-01', today) %>% 
    select(Country, Continent, `Total Cases per Million`) %>%
    reactable::reactable(rownames = FALSE)
```



Map
=======================================================================

Column {data-width=300 .sidebar}
-----------------------------------------------------------------------

```{r, fig.align='center'}
h1("\n\n\n\n\n\n\n\n")

dateRangeInput("date_range_map", strong("Date Range"), start = as.Date("2020-01-01"), end = end)

actionButton("view_map", "View")
```

```{r}
tags$footer(HTML(paste0("<footer><small><b>Updated ", time_since_last_commit, " hours ago.</b></small></footer>")), align = "left", style = "position:absolute; bottom:0; width:95%; height:50px; color: #000000; padding: 0px; background-color: transparent; z-index: 1000;")
```



Column {data-width=1000}
-----------------------------------------------------------------------

### Interactive Map


```{r, fig.height=9}

mcd <- eventReactive(input$view_map, {
  global_summary(input$date_range_map[1], input$date_range_map[2], maps)
})

renderLeaflet({
  maps2 <- mcd()

pal <- colorNumeric(palette = 'Blues',
                    domain = log10(maps2@data$total_cases))

label <- paste0(
    '<b>Country: ', maps2$location, 
    '</b><br/>- Population:', ifelse(is.na(maps2$population), 'No info', prettyNum(maps2$population, big.mark = ",")),
    '<br/>- Total Cases: ', ifelse(maps2$total_cases == 1, 0, prettyNum(maps2$total_cases, big.mark = ",")),
    '<br/>- Total Deaths: ', prettyNum(maps2$total_deaths, big.mark = ','),
    '<br/>- Positive Rate: ', ifelse(is.infinite(maps2$positivity), 'No info', paste0(prettyNum(maps2$positivity, big.mark = ','), '%')),
    '<br/>- Total Cases per Millon: ', prettyNum(maps2$cases_pm, big.mark = ","),
    '<br/>- Total Deaths per Millon: ', prettyNum(maps2$deaths_pm, big.mark = ",")
)

maps2 %>% 
    leaflet(options = leafletOptions(minZoom = 2)) %>%
    addProviderTiles('CartoDB') %>%
    addSearchOSM() %>%
    addResetMapButton() %>% 
    addPolygons(weight      = 1, 
                color       = ~ pal(log10(total_cases)), 
                fillOpacity = 1,
                popup       = ~ label,
                highlightOptions = highlightOptions(
                    weight       = 5, 
                    color        = "white",
                    bringToFront = TRUE
                ))

})
```

Country
=======================================================================

Column {data-width=300 .sidebar}
-----------------------------------------------------------------------

```{r, fig.align='center'}
h1("\n\n\n\n\n\n\n\n")

dateRangeInput("date_range_country", strong("Date Range"), start = as.Date("2020-01-01"), end = end)

selectInput("s_continent", strong("Continent"), choices = continents, selected = continents[1])

conditionalPanel(
  "input.s_continent == 'Africa'",
  selectInput("scountry1", strong("Country"),
    choices = countries_per_continent$Africa,
    selected = countries_per_continent$Africa[1]
  )
)
conditionalPanel(
  "input.s_continent == 'Asia'",
  selectInput("scountry2", strong("Country"),
    choices = countries_per_continent$Asia,
    selected = countries_per_continent$Asia[1]
  )
)
conditionalPanel(
  "input.s_continent == 'Europe'",
  selectInput("scountry3", strong("Country"),
    choices = countries_per_continent$Europe,
    selected = countries_per_continent$Europe[1]
  )
)
conditionalPanel(
  "input.s_continent == 'North America'",
  selectInput("scountry4", strong("Country"),
    choices = countries_per_continent$`North America`,
    selected = countries_per_continent$`North America`[1]
  )
)
conditionalPanel(
  "input.s_continent == 'Oceania'",
  selectInput("scountry5", strong("Country"),
    choices = countries_per_continent$Oceania,
    selected = countries_per_continent$Oceania[1]
  )
)
conditionalPanel(
  "input.s_continent == 'South America'",
  selectInput("scountry6", strong("Country"),
    choices = countries_per_continent$`South America`,
    selected = countries_per_continent$`South America`[1]
  )
)
```
```{r}
actionButton("view_country", "View")

tags$footer(HTML(paste0("<footer><small><b>Updated ", time_since_last_commit, " hours ago.</b></small></footer>")), align = "left", style = "position:absolute; bottom:0; width:95%; height:50px; color: #000000; padding: 0px; background-color: transparent; z-index: 1000;")
```


Column {data-width=290}
-----------------------------------------------------------------------

```{r}
cs <- eventReactive(input$view_country, {
  if (input$s_continent == "Africa") {
    data <- country_summary(
      start = input$date_range_country[1],
      end = input$date_range_country[2],
      country = input$scountry1
    )
  } else if (input$s_continent == "Asia") {
    data <- country_summary(
      start = input$date_range_country[1],
      end = input$date_range_country[2],
      country = input$scountry2
    )
  } else if (input$s_continent == "Europe") {
    data <- country_summary(
      start = input$date_range_country[1],
      end = input$date_range_country[2],
      country = input$scountry3
    )
  } else if (input$s_continent == "North America") {
    data <- country_summary(
      start = input$date_range_country[1],
      end = input$date_range_country[2],
      country = input$scountry4
    )
  } else if (input$s_continent == "Oceania") {
    data <- country_summary(
      start = input$date_range_country[1],
      end = input$date_range_country[2],
      country = input$scountry5
    )
  } else if (input$s_continent == "South America") {
    data <- country_summary(
      start = input$date_range_country[1],
      end = input$date_range_country[2],
      country = input$scountry6
    )
  }

  data
})
```

### $\,$

```{r}
renderValueBox({
  cs <- cs()


  valueBox(
    value = cs$interval_covid_data$location[1],
    caption = "Country",
    color = "#808080"
  ) # ,
  # icon = 'fo-virus')
})
```

### New Cases in Date Range


```{r}
renderEcharts4r({
  cs()$interval_covid_data %>% 
    rename('New Cases' = new_cases) %>% 
    e_charts(x = date) %>% 
    e_bar_('New Cases',
           itemStyle = list(color = '#0f1955',
                            opacity = 0.7)) %>% 
    e_tooltip(trigger = 'axis') %>% 
    e_axis_labels(x = 'Date',
                  y = 'New Cases') %>% 
    e_legend(show = FALSE) %>% 
    e_toolbox_feature("dataZoom") %>%
    e_toolbox_feature(feature = "reset") %>%
    e_toolbox_feature("dataView") %>%
    e_toolbox_feature("saveAsImage") %>% 
    e_datazoom(
        type = "slider", 
        toolbox = FALSE,
        bottom = 12
    ) %>% 
    e_x_axis(nameLocation = "center", 
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_y_axis(nameLocation = "center", 
             position = 'right',
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_theme_custom('codes//walden.project.json')
}
)
```





### Accumuled Cases in Date Range

```{r}
renderEcharts4r({
  cs()$interval_covid_data %>% 
    rename('Total Cases' = total_cases) %>% 
    e_charts(x = date) %>% 
    e_bar_('Total Cases',
           itemStyle = list(color = '#0f1955',
                            opacity = 0.7)) %>% 
    e_tooltip(trigger = 'axis') %>% 
    e_axis_labels(x = 'Date',
                  y = 'Total Cases') %>% 
    e_legend(show = FALSE) %>% 
    e_toolbox_feature("dataZoom") %>%
    e_toolbox_feature(feature = "reset") %>%
    e_toolbox_feature("dataView") %>%
    e_toolbox_feature("saveAsImage") %>% 
    e_datazoom(
        type = "slider", 
        toolbox = FALSE,
        bottom = 12
    ) %>% 
    e_x_axis(nameLocation = "center", 
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_y_axis(nameLocation = "center", 
             position = 'right',
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_theme_custom('codes//walden.project.json')
}
)
```


### Accumuled Deaths in Date Range

```{r}
renderEcharts4r({
  cs()$interval_covid_data %>% 
    rename('Total Deaths' = total_deaths) %>% 
    e_charts(x = date) %>% 
    e_bar_('Total Deaths',
           itemStyle = list(color = '#000000',
                            opacity = 0.7)) %>% 
    e_tooltip(trigger = 'axis') %>% 
    e_axis_labels(x = 'Date',
                  y = 'Total Deaths') %>% 
    e_legend(show = FALSE) %>% 
    e_toolbox_feature("dataZoom") %>%
    e_toolbox_feature(feature = "reset") %>%
    e_toolbox_feature("dataView") %>%
    e_toolbox_feature("saveAsImage") %>% 
    e_datazoom(
        type = "slider", 
        toolbox = FALSE,
        bottom = 12
    ) %>% 
    e_x_axis(nameLocation = "center", 
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_y_axis(nameLocation = "center", 
             position = 'right',
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_theme_custom('codes//walden.project.json')
}
)
```


### Accumuled Tests in Date Range

```{r}
renderEcharts4r({
  cs()$interval_covid_data %>% 
    rename('Total Tests' = total_tests,
           itemStyle = list(color = '#bf8cff',
                            opacity = 0.7)) %>% 
    e_charts(x = date) %>% 
    e_bar_('Total Tests') %>% 
    e_tooltip(trigger = 'axis') %>% 
    e_axis_labels(x = 'Date',
                  y = 'Total Tests') %>% 
    e_legend(show = FALSE) %>% 
    e_toolbox_feature("dataZoom") %>%
    e_toolbox_feature(feature = "reset") %>%
    e_toolbox_feature("dataView") %>%
    e_toolbox_feature("saveAsImage") %>% 
    e_datazoom(
        type = "slider", 
        toolbox = FALSE,
        bottom = 12
    ) %>% 
    e_x_axis(nameLocation = "center", 
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_y_axis(nameLocation = "center", 
             position = 'right',
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_theme_custom('codes//walden.project.json')
}
)
```

Column {data-width=290}
-----------------------------------------------------------------------

### $\,$

```{r}
renderValueBox({
  cs <- cs()


  valueBox(
    value = prettyNum(cs$interval_covid_data$population[1], big.mark = ","),
    caption = "Population",
    color = "#808080"
  ) # ,
  # icon = 'fo-virus')
})
```

### Active Cases in Date Range

```{r}
renderEcharts4r({
  cs()$interval_covid_data %>% 
    rename('Total Active' = total_active) %>% 
    e_charts(x = date) %>% 
    e_bar_('Total Active',
           itemStyle = list(color = '#0f1955',
                            opacity = 0.7)) %>% 
    e_tooltip(trigger = 'axis') %>% 
    e_axis_labels(x = 'Date',
                  y = 'Total Active') %>% 
    e_legend(show = FALSE) %>% 
    e_toolbox_feature("dataZoom") %>%
    e_toolbox_feature(feature = "reset") %>%
    e_toolbox_feature("dataView") %>%
    e_toolbox_feature("saveAsImage") %>% 
    e_datazoom(
        type = "slider", 
        toolbox = FALSE,
        bottom = 12
    ) %>% 
    e_x_axis(nameLocation = "center", 
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_y_axis(nameLocation = "center", 
             position = 'right',
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_theme_custom('codes//walden.project.json')
}
)
```

### New Deaths in Date Range

```{r}
renderEcharts4r({
  cs()$interval_covid_data %>% 
    rename('New Deaths' = new_deaths) %>% 
    e_charts(x = date) %>% 
    e_bar_('New Deaths',
           itemStyle = list(color = '#000000',
                            opacity = 0.7)) %>% 
    e_tooltip(trigger = 'axis') %>% 
    e_axis_labels(x = 'Date',
                  y = 'New Deaths') %>% 
    e_legend(show = FALSE) %>% 
    e_toolbox_feature("dataZoom") %>%
    e_toolbox_feature(feature = "reset") %>%
    e_toolbox_feature("dataView") %>%
    e_toolbox_feature("saveAsImage") %>% 
    e_datazoom(
        type = "slider", 
        toolbox = FALSE,
        bottom = 12
    ) %>% 
    e_x_axis(nameLocation = "center", 
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_y_axis(nameLocation = "center", 
             position = 'right',
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_theme_custom('codes//walden.project.json')
}
)
```


### New Tests in Date Range

```{r}
renderEcharts4r({
  cs()$interval_covid_data %>% 
    rename('New Tests' = new_tests) %>% 
    e_charts(x = date) %>% 
    e_bar_('New Tests',
           itemStyle = list(color = '#bf8cff',
                            opacity = 0.7)) %>% 
    e_tooltip(trigger = 'axis') %>% 
    e_axis_labels(x = 'Date',
                  y = 'New Tests') %>% 
    e_legend(show = FALSE) %>% 
    e_toolbox_feature("dataZoom") %>%
    e_toolbox_feature(feature = "reset") %>%
    e_toolbox_feature("dataView") %>%
    e_toolbox_feature("saveAsImage") %>% 
    e_datazoom(
        type = "slider", 
        toolbox = FALSE,
        bottom = 12
    ) %>% 
    e_x_axis(nameLocation = "center", 
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_y_axis(nameLocation = "center", 
             position = 'right',
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_theme_custom('codes//walden.project.json')
}
)
```


### Positive Rate in Date Range

```{r}
renderEcharts4r({
  cs()$interval_covid_data %>% 
    rename('Positive Rate' = positive_rate) %>% 
    e_charts(x = date) %>% 
    e_line_('Positive Rate',
           lineStyle = list(color = '#368fce',
                            opacity = 0.7)) %>% 
    e_tooltip(trigger = 'axis') %>% 
    e_axis_labels(x = 'Date',
                  y = 'Positive Rate') %>% 
    e_legend(show = FALSE) %>% 
    e_toolbox_feature("dataZoom") %>%
    e_toolbox_feature(feature = "reset") %>%
    e_toolbox_feature("dataView") %>%
    e_toolbox_feature("saveAsImage") %>% 
    e_datazoom(
        type = "slider", 
        toolbox = FALSE,
        bottom = 12
    ) %>% 
    e_x_axis(nameLocation = "center", 
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0)) %>% 
    e_y_axis(nameLocation = "center", 
             position = 'right',
             splitArea = list(show = FALSE),
             axisLabel = list(margin = 0),
             formatter = e_axis_formatter('percent', digits = 2)) %>% 
    e_theme_custom('codes//walden.project.json')
}
)
```


Column {data-width=120}
-----------------------------------------------------------------------

### $\,$

```{r}
renderValueBox({
  cs <- cs()


  valueBox(
    value = prettyNum(cs$new_cases, big.mark = ","),
    caption = paste0("New cases in ", input$date_range_country[2]),
    color = "#36479C",
    icon = "fa-viruses"
  )
})
```

### $\,$

```{r}
renderValueBox({
  cs <- cs()


  valueBox(
    value = prettyNum(cs$active_cases, big.mark = ","),
    caption = paste0("Active cases in ", input$date_range_country[2]),
    color = "#36479C"
  ) # ,
  # icon = 'fo-virus')
})
```

### $\,$

```{r}
renderValueBox({
  cs <- cs()


  valueBox(
    value = prettyNum(cs$cases_pm, big.mark = ","),
    caption = paste0("Total cases per million in Date Range"),
    color = "#36479C"
  ) # ,
  # icon = 'fo-virus')
})
```


### $\,$

```{r}
renderValueBox({
  cs <- cs()


  valueBox(
    value = prettyNum(cs$total_recovered, big.mark = ","),
    caption = paste0("Total recovered in ", input$date_range_country[2]),
    color = "#36479C"
  ) # ,
  # icon = 'fo-virus')
})
```

### $\,$

```{r}
renderValueBox({
  cs <- cs()


  valueBox(
    value = prettyNum(cs$total_cases, big.mark = ","),
    caption = paste0("Total cases in Data Range"),
    color = "#36479C"
  ) # ,
  # icon = 'fo-virus')
})
```


### $\,$

```{r}
renderValueBox({
  cs <- cs()


  valueBox(
    value = prettyNum(cs$last_day_deaths, big.mark = ","),
    caption = paste0("New deaths in ", input$date_range_country[2]),
    color = "#36479C"
  ) # ,
  # icon = 'fo-virus')
})
```

### $\,$

```{r}
renderValueBox({
  cs <- cs()


  valueBox(
    value = prettyNum(cs$total_death, big.mark = ","),
    caption = paste0("Total deaths in Date Range"),
    color = "#36479C"
  ) # ,
  # icon = 'fa-virus')
})
```


### $\,$

```{r}
renderValueBox({
  cs <- cs()


  valueBox(
    value = prettyNum(cs$total_test, big.mark = ","),
    caption = paste0("Total tests in Date Range"),
    color = "#8ec3a7"
  ) # ,
  # icon = 'fo-virus')
})
```

### $\,$

```{r}
renderValueBox({
  cs <- cs()


  valueBox(
    value = ifelse(is.infinite(cs$total_positivity),
      "No data",
      paste0(cs$total_positivity, "%")
    ),
    caption = paste0("Positive rate in Date Range"),
    color = "#8ec3a7"
  ) # ,
  # icon = 'fo-virus')
})
```

### $\,$

```{r}
renderValueBox({
  cs <- cs()


  valueBox(
    value = prettyNum(cs$test_last_day, big.mark = ","),
    caption = paste0("New tests in ", input$date_range_country[2]),
    color = "#8ec3a7"
  ) # ,
  # icon = 'fo-virus')
})
```

### $\,$

```{r}
renderValueBox({
  cs <- cs()


  valueBox(
    value = ifelse(is.infinite(cs$positivity_last_day),
      "No data",
      paste0(cs$positivity_last_day, "%")
    ),
    caption = paste0("Positive rate in ", input$date_range_country[2]),
    color = "#8ec3a7"
  ) # ,
  # icon = 'fo-virus')
})
```
